name: learn-github-actions
on:
  push:
    branches:
      - release
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: ./github_gnu_build.sh
      - name: unittest
        run: ./app unittest
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: application
          path: app
  mac-build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: ./github_mac_build.command
      - name: unittest
        run: ./app unittest

